// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSource(arg1) {
  return window['go']['main']['App']['DeleteSource'](arg1);
}

export function DisableSource(arg1) {
  return window['go']['main']['App']['DisableSource'](arg1);
}

export function EnableSource(arg1) {
  return window['go']['main']['App']['EnableSource'](arg1);
}

export function GetLyric(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLyric'](arg1, arg2, arg3);
}

export function GetMusicURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMusicURL'](arg1, arg2, arg3, arg4);
}

export function GetPic(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPic'](arg1, arg2, arg3);
}

export function GetSourceDataDir() {
  return window['go']['main']['App']['GetSourceDataDir']();
}

export function ImportSource() {
  return window['go']['main']['App']['ImportSource']();
}

export function ListSources() {
  return window['go']['main']['App']['ListSources']();
}

export function Search(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3, arg4);
}
