// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {music} from '../models';

export function DeleteSource(arg1:string):Promise<void>;

export function DisableSource(arg1:string):Promise<music.SourceInfo>;

export function EnableSource(arg1:string):Promise<music.SourceInfo>;

export function GetLyric(arg1:string,arg2:string,arg3:string):Promise<music.LyricInfo>;

export function GetMusicURL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetPic(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSourceDataDir():Promise<string>;

export function ImportSource():Promise<music.SourceInfo>;

export function ListSources():Promise<Array<music.SourceInfo>>;

export function Search(arg1:string,arg2:string,arg3:string,arg4:number):Promise<music.SearchResult>;
