// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function AddPlaylistSong(arg1, arg2) {
  return window['go']['main']['App']['AddPlaylistSong'](arg1, arg2);
}

export function ClearRecent() {
  return window['go']['main']['App']['ClearRecent']();
}

export function CreatePlaylist(arg1) {
  return window['go']['main']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function GetLocalAudioStream(arg1) {
  return window['go']['main']['App']['GetLocalAudioStream'](arg1);
}

export function GetLocalSongCovers(arg1) {
  return window['go']['main']['App']['GetLocalSongCovers'](arg1);
}

export function GetLocalSongExtras(arg1) {
  return window['go']['main']['App']['GetLocalSongExtras'](arg1);
}

export function GetLyric(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLyric'](arg1, arg2, arg3);
}

export function GetMusicURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMusicURL'](arg1, arg2, arg3, arg4);
}

export function GetPic(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPic'](arg1, arg2, arg3);
}

export function GetPlaylist(arg1) {
  return window['go']['main']['App']['GetPlaylist'](arg1);
}

export function GetSourceDataDir() {
  return window['go']['main']['App']['GetSourceDataDir']();
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function ListFavorites() {
  return window['go']['main']['App']['ListFavorites']();
}

export function ListLocalFolders() {
  return window['go']['main']['App']['ListLocalFolders']();
}

export function ListLocalLibrary() {
  return window['go']['main']['App']['ListLocalLibrary']();
}

export function ListPlaylists() {
  return window['go']['main']['App']['ListPlaylists']();
}

export function ListRecent() {
  return window['go']['main']['App']['ListRecent']();
}

export function PickLocalMusicFolder() {
  return window['go']['main']['App']['PickLocalMusicFolder']();
}

export function RecordRecent(arg1) {
  return window['go']['main']['App']['RecordRecent'](arg1);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RemoveLocalMusicFolder(arg1) {
  return window['go']['main']['App']['RemoveLocalMusicFolder'](arg1);
}

export function RemovePlaylistSong(arg1, arg2) {
  return window['go']['main']['App']['RemovePlaylistSong'](arg1, arg2);
}

export function RemoveRecent(arg1) {
  return window['go']['main']['App']['RemoveRecent'](arg1);
}

export function ScanLocalLibrary() {
  return window['go']['main']['App']['ScanLocalLibrary']();
}

export function Search(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3, arg4);
}
